import type { Metadata } from "next";
import { Nunito } from "next/font/google";

import { Header } from "@/shared/components/shared/header";
import { Suspense } from "react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode;
  modal: any
}>) {
  return (
 <Suspense>
        <main className="min-h-screen">
          <Header />
        {children}
        {modal}
        </main>
        </Suspense>
  );
}
